### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by Raiper34** [phaser-cli/phaser-cli#6]
Any chance to work with this great tool and typescript?

Thanks.

**Comment by nerdenough** [comment]
`phaser-cli` itself doesn't set what language is supported, these are done through each of the templates - which can contain whatever boilerplate you need for your projects. I haven't made any Typescript templates as of yet, but my `simple` and `webpack` ones can be found [here](https://github.com/phaser-templates). I don't use Typescript so I wouldn't know what packages are good to have with it 😛 

If you keep a similar structure to those templates (i.e. putting the template that is downloaded by `phaser-cli` into the `templates` folder), you should be able to create your own template with Typescript support. Then you can run `phaser init username/repo my-project` (your Github user/repo) to create a project based on that template.

Closing as this is a templating issue rather than `phaser-cli`, but happy to help if you have any more questions about that.
